#!/usr/bin/env python3
"""Build Kaggle bundle from the current T4 notebook, preserving student code.

    python scripts/build_kaggle.py
    python scripts/build_kaggle.py --check
"""
from __future__ import annotations

import argparse
import ast
import json
from pathlib import Path

from build_colab import code, md, requirements, source_lines

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "colab" / "Lab22_DPO_T4.ipynb"
TARGET = REPO / "kaggle" / "Lab22_DPO_T4.ipynb"
WORKDIR = "/kaggle/working/lab22"


def render() -> dict:
    nb = json.loads(SOURCE.read_text(encoding="utf-8"))
    nb["metadata"] = {
        "kernelspec": {"display_name": "Python 3", "name": "python3"},
        "language_info": {"name": "python"},
        "accelerator": "GPU",
    }
    cells = nb["cells"]
    cells[0] = md(
        "# Lab 22 — DPO/ORPO Alignment · Kaggle T4\n\n"
        "Generated by `scripts/build_kaggle.py` from the current Colab notebook; "
        "student solutions are preserved, old outputs are cleared.\n\n"
        "**Settings:** Accelerator = GPU T4 x2 (or a compatible single GPU); Internet = On. "
        "Run setup in a fresh session, before importing torch, transformers or trl. "
        "If those packages were already imported, restart the session first.\n\n"
        "This notebook exposes only GPU 0. Two T4s do not form one 32 GB GPU; "
        "the existing single-GPU Unsloth/4-bit pipeline keeps its 16 GB T4 settings. "
        "FP16/BF16 remains selected by the existing GPU capability check.\n\n"
        "Run NB0 → NB4; NB3b and NB5–NB7 are optional. "
        "Core setup skips GGUF/benchmark/API-judge dependencies. "
        "Bonus dependencies install only when their sections are run.\n\n"
        "Outputs: `/kaggle/working/lab22`. Use **Save Version** and verify the saved "
        "version's Output files before ending the session. Files in `/kaggle/temp` "
        "are disposable caches, not recovery data. Save completed stages before quota runs out.\n\n"
        "To migrate Colab progress, attach a private Kaggle Dataset containing your "
        "`lab22` output folder. Set `RESTORE_FROM` in setup to its exact directory "
        "under `/kaggle/input`, containing `models`, `adapters`, `data`, and/or `submission`. "
        "Rerun setup, then continue from the next completed stage. This restores stage "
        "artifacts, not interrupted optimizer state; incomplete training must restart.\n\n"
        "Local reward judges need no API keys. For optional API judges, use Kaggle Secrets "
        "and enable notebook access. Install `%pip install openai` for OpenAI or "
        "`%pip install anthropic` for Anthropic before NB4; Gemini uses the stdlib HTTP client. "
        "Never put keys in notebook source or outputs."
    )
    cells[2] = code(
        "import os\n"
        "import sys\n"
        'if any(name in sys.modules for name in ("torch", "transformers", "trl", "unsloth")):\n'
        '    raise RuntimeError("Restart the Kaggle session, then run setup before GPU imports.")\n'
        'os.environ["CUDA_VISIBLE_DEVICES"] = "0"\n'
        'os.environ["COMPUTE_TIER"] = "T4"\n'
        'os.environ["HF_HOME"] = "/kaggle/temp/huggingface"\n'
        'os.environ["PIP_CACHE_DIR"] = "/kaggle/temp/pip"\n'
        'os.environ["TOKENIZERS_PARALLELISM"] = "false"\n'
        'RESTORE_FROM = ""  # Optional: /kaggle/input/<dataset>/lab22\n'
        '# os.environ["JUDGE_PROVIDER"] = "gemini"\n'
        '# os.environ["JUDGE_MODEL"] = "<current model id>"\n'
        '# from kaggle_secrets import UserSecretsClient\n'
        '# os.environ["GEMINI_API_KEY"] = UserSecretsClient().get_secret("GEMINI_API_KEY")'
    )
    optional = ("llama-cpp-python", "lm-eval", "openai", "anthropic")
    core = [s for s in requirements() if not s.startswith(optional)]
    cells[3] = code('%pip install -q ' + " ".join(f'"{s}"' for s in core))
    cells[4] = code(
        "from pathlib import Path\n"
        "import shutil\n"
        f'WORK = Path("{WORKDIR}")\n'
        'if RESTORE_FROM:\n'
        '    source = Path(RESTORE_FROM).resolve()\n'
        '    if not source.is_relative_to(Path("/kaggle/input")) or not source.is_dir():\n'
        '        raise ValueError("RESTORE_FROM must be an existing directory under /kaggle/input")\n'
        '    names = [name for name in ("models", "adapters", "data", "submission")\n'
        '             if (source / name).is_dir()]\n'
        '    if not names:\n'
        '        raise ValueError("RESTORE_FROM contains no lab stage artifacts")\n'
        '    if any((WORK / name).exists() for name in names):\n'
        '        raise FileExistsError("Restore would overwrite artifacts; clear RESTORE_FROM to reuse working files")\n'
        '    for name in names:\n'
        '        shutil.copytree(source / name, WORK / name)\n'
        '(WORK / "lab22").mkdir(parents=True, exist_ok=True)\n'
        'os.chdir(WORK)\n'
        'import unsloth  # Must patch transformers before GPU imports.\n'
        'import torch\n'
        'if not torch.cuda.is_available():\n'
        '    raise RuntimeError("Enable GPU accelerator in Kaggle Settings")\n'
        'if torch.cuda.device_count() != 1:\n'
        '    raise RuntimeError("Multiple GPUs remain visible. Restart session and run CUDA_VISIBLE_DEVICES setup first.")\n'
        'print(Path.cwd(), torch.cuda.get_device_name(0))\n'
        'print(f"Visible GPUs: {torch.cuda.device_count()}; VRAM: {torch.cuda.get_device_properties(0).total_memory / 2**30:.1f} GiB")'
    )
    result = []
    for cell in cells:
        text = "".join(cell["source"]).replace("/content/lab22", WORKDIR)
        if text.startswith(f"%%writefile {WORKDIR}/lab22/modeling.py"):
            text = text.replace(
                "        load_in_4bit=load_in_4bit,\n",
                '        load_in_4bit=load_in_4bit,\n        device_map={"": 0},\n',
                1,
            )
        if cell["cell_type"] == "markdown" and "# ⏵ `notebooks/05_merge_deploy_gguf.py`" in text:
            result.append(md(
                "## Core complete — save outputs before optional bonuses\n\n"
                "NB4 finishes required work. Save a version and verify Output files. "
                "NB5–NB7 consume extra disk, GPU quota and install time; skip unless needed."
            ))
            result.append(code('%pip install -q "llama-cpp-python>=0.3.16,<1.0"'))
        if cell["cell_type"] == "markdown" and "# ⏵ `notebooks/06_benchmark.py`" in text:
            result.append(code('%pip install -q "lm-eval[ifeval,math]>=0.4.13,<0.5"'))
        cell["source"] = source_lines(text)
        cell["metadata"] = {}
        if cell["cell_type"] == "code":
            cell["execution_count"] = None
            cell["outputs"] = []
        result.append(cell)
    nb["cells"] = result
    return nb


def validate(nb: dict) -> None:
    for cell in nb["cells"]:
        text = "".join(cell["source"])
        assert "/content/" not in text and "google.colab" not in text
        if cell["cell_type"] != "code":
            continue
        assert cell["outputs"] == [] and cell["execution_count"] is None
        if text.startswith("%%writefile"):
            text = text.split("\n", 1)[1]
        if text.startswith(("%pip", "!")):
            continue
        ast.parse(text)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    nb = render()
    validate(nb)
    if args.check:
        assert TARGET.exists() and json.loads(TARGET.read_text(encoding="utf-8")) == nb, "Kaggle bundle stale; run python scripts/build_kaggle.py"
    else:
        TARGET.parent.mkdir(exist_ok=True)
        TARGET.write_text(json.dumps(nb, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        print(f"wrote {TARGET} ({len(nb['cells'])} cells)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
